### ISSUE TITLE
unused BS pin

### ISSUE THREAD

**Issue by atsju** [PervasiveDisplays/ePaper_PervasiveDisplays#3]
Hi @CharmingSu @Hardycool 
I see that in the code there is a definition of BS_PIN but it is not used. What is it for ? or remove it from code

**Comment by Hardycool** [comment]
@atsju  Thank you for your question, BS_PIN can be controlled either in the code or directly tied to the GND. We reserve this hardware configuration in the code in order to provide a flexible hardware manipulation.

**Comment by atsju** [comment]
Thank you. I have seen in the documentation of some screens "This pin is setting panel interface." and tied to GND.
It is quite difficult to find all relevant information. Every screen do not have dedicated datasheet with "reference circuit" and it's difficult to understand what is really needed or not depending on the screen. 
Can you confirm what this pin may be used for, and what means  "This pin is setting panel interface." ? If it's always tied to GND why isn't it done in the schematic ?

**Comment by CharmingSu** [comment]
The BS pin means Bus Selection to select 3-wires or 4-wires SPI interface.  Low for 4-wires and high for 3-wires. In our setting of SPI, we use 4-wires so please set it in Low can be connected to GND.

**Comment by atsju** [comment]
Thank you, now I have a better understanding.
